name: CI
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npx nx run-many -t lint -p meta-injector meta-injector-react
      - name: Test
        run: npx nx run-many -t test -p meta-injector meta-injector-react --coverage --configuration=ci
      - name: Build
        run: npx nx run-many -t build -p meta-injector meta-injector-react --configuration=production
